# Generated by Django 4.0.3 on 2022-03-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='position',
        ),
        migrations.AddField(
            model_name='interview',
            name='participants',
            field=models.ManyToManyField(to='main_page.participant'),
        ),
    ]
