# Generated by Django 4.0.3 on 2022-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_participant_remove_interview_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Interviewer', 'Interviewer')], max_length=11),
        ),
    ]
