# Generated by Django 4.0.3 on 2022-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_participant_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Interviewer', 'Interviewer')], default='candidate', max_length=11),
        ),
    ]
