# Generated by Django 4.0.3 on 2022-03-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_participant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
    ]
